# ---
# - name: Provision a new k3s cluster controller
#   hosts: controller
#   roles:
#     - role: k3s-controller

# - name: Provision the k3s cluter workers
#   hosts: workers
#   roles:
#     - role: k3s-worker

# - name: Provision a new k3s cluster controller
#   hosts: controller
#   roles:
#     - role: k3s-worker-roles
#     - role: k3s-helm-controller
#     - role: k3s-loadbalancer

# - name: Provision longhorn storage on all works
#   hosts: nodes
#   roles:
#     - role: k3s-storage-common

# - name: Provision longhorn controller
#   hosts: controller
#   roles:
#     - role: k3s-storage-controller

- name: Docker registry
  hosts: controller
  roles:
    - role: k3s-docker-registry
