---
- name: Create and start raspberry pi vms on host
  hosts: vm-hosts
  become: true

  tasks:

    - name: Verify virtualization capabilities of the host
      ansible.builtin.shell:
        cmd: |-
          LC_ALL=C lscpu | grep Virtualization: | sed -e 's/^.*Virtualization:\s*\(.*\)\s*$/\1/'
      register: ret
      failed_when: ret.stdout != 'VT-x' and ret.stdout != 'AMD-V'

    - name: Verify that qemu-system-aarch64 package is present
      ansible.builtin.pacman:
        name: qemu-system-aarch64
        state: present
