- name: Install Longhorn IO prereqs on all nodes
  apt:
    pkg:
      - python3-pip
    state: present

- name: Install PyYAML python package
  ansible.builtin.pip:
    name: PyYAML

- name: Add longhorn repository to the controller
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "{{ longhorn_helm_repourl }}"

- name: Install longhorn via helm
  kubernetes.core.helm:
   name: longhorn
   chart_ref: longhorn/longhorn
   release_namespace: "{{ longhorn_namespace }}"
   create_namespace: true
   update_repo_cache: True
   set_values:
     - value: service.ui.loadBalancerIP="{{ longhorn_loadbalancer_ip }}"
       value_type: string
     - value: service.ui.type=LoadBalancer
       value_type: string
     - value: defaultSettings.defaultDataPath="{{ longhorn_storage_dir }}"
       value_type: string
