apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ docker_reg_namespace }}-certificate
  namespace: {{ docker_reg_namespace }}
spec:
  secretName: {{ docker_reg_namespace }}-secret
  dnsNames:
  - "*.{{ docker_reg_namespace }}.svc.cluster.local"
  - "*.{{ docker_reg_namespace }}"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
#    group: cert-manager.io/v1
