apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ docker_reg_pvc_name }}
  namespace: {{ docker_reg_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ docker_reg_pvc_size }}
