apiVersion: v1
data:
  tls.crt: {{ lookup('file', ca_crt ) | b64encode }}
  tls.key: {{ lookup('file', ca_key ) | b64encode }}
kind: Secret
metadata:
  name: {{ ca_secret }}
  namespace: {{ cert_manager_namespace }}
type: kubernetes.io/tls
