apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ cert_manager_namespace }}-issuer
  namespace: {{ cert_manager_namespace }}
spec:
  ca:
    secretName: ca-secret
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: {{ cert_manager_namespace }}-ca
#   namespace: {{ cert_manager_namespace }}
# spec:
#   isCA: true
#   commonName: {{ cert_manager_namespace }}-ca
#   secretName: ca-secret
#   privateKey:
#     algorithm: ECDSA
#     size: 256
#   issuerRef:
#     name: {{ cert_manager_namespace }}-issuer
#     kind: ClusterIssuer
#     group: cert-manager.io
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: ca-issuer
# spec:
#   ca:
#     secretName: ca-secret
